---
title: RMarkdown e websites
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_folding: hide
---

# Introdução

Esta atividade tem como intuito ensinar a criar um *website* utilizando
os pacotes do *R*, mais especificamente o RMarkdown.
Vamos utilizar o Github para hostear o nosso site, já que esta função
é gratuita na plataforma.

# Configurando o arquivo _site.yml

Crie um arquivo chamado *_site.yml* e dentro dele adicione

    /name: "Meu site"
    output_dir: "."
    output:
      html_document:
        theme: paper
        includes:
          #before_body: before_.html
          #after_body: after.html
        #css: style_.css
    navbar:
      left:
        - text: "Home"
          href: index.html
        - text: "Projetos"
          href: projeto.html
          menu:
            - text: "Projeto 2"
              href: "projetos2.html"

Para maiores detalhes sobre como preencher e customizar esse arquivo, acesse este
<a href="http://rmarkdown.rstudio.com/rmarkdown_websites.html">site</a>.

# Inicializando o site

Crie um arquivo nomeado **index.Rmd**. Após isto, adicione no pré-âmbulo.

    title: RStudio e websites
    output:
      html_document:
        toc: true
        toc_float: true
        number_sections: true
        code_folding: hide

Preencha o campo **title** com o nome do seu site.

O campo **output** é onde você indica o tipo de saída quando renderizamos o
site. Neste caso, vamos escolher *html_document*.

Já o campo **toc** é onde podemos colocar *true* ou *false*, que nos diz se
queremos o sumário da página ou não.

O **toc_float** nos diz se o sumário vai nos acompanhar enquanto navegamos
pela página.

O item **number_sections** indica se queremos numeração nas seções.

E por último, o campo **code_folding** é para *esconder* o código, sendo que
se o leitor quiser visualizar o código, ele deve pressionar o botão
*Code* e depois *Show All Code*.

Para mais informações, acesse em <a href="projetos2.html">Projeto</href>
